version: "3.7"

services:

    mysql1:
        image: bayrell/alpine_mariadb:10.4-20200426_165923
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode="" --ft_min_word_len=1 --wait_timeout=600 --max_allowed_packet=1G
        hostname: "{{.Service.Name}}.{{.Task.ID}}.local"
        volumes:
            - "mysql1_data:/data"
        env_file:
            - common.env
        environment:
            MYSQL_ROOT_USERNAME: "lasto4ka"
            MYSQL_ROOT_PASSWORD: "7DF&d7jr!Lk5rZ^b"
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                failure_action: rollback
                delay: 5s
            restart_policy:
                condition: "on-failure"
                delay: 10s
                window: 120s
            placement:
                constraints:
                    - node.hostname == raspberrypi
        networks:
            - backend
        logging:
            driver: journald

volumes:
    mysql1_data:

networks:

    backend:
        driver: overlay
        attachable: true
